### DISCUSSION TITLE
Multiple Hostname (virtual host?)

### DISCUSSION THREAD

**Discussion by DamianoP** [huan/docker-simple-mail-forwarder#78] [General]
Hi all,

this is my docker compose file:
```
version: '3'
services:
  mailserver:
    image: zixia/simple-mail-forwarder:1.1
    container_name: mailserver
    hostname: mailserver1.org
    environment:
      - SMF_CONFIG=@mailserver1.org:mypersonalemail@gmail.com;@mailserver2.org:mypersonalemail@gmail.com
    ports:
      - "25:25"
    restart: always
```
The ip and MX records are configured correctly, however emails are only forwarded when received by mailserver2
How can I solve the problem ?

**Comment by DamianoP** [comment]
I found a possible solution to the problem

this is the modified docker compose file:
```
version: '3'
services:
  mailserver:
    image: zixia/simple-mail-forwarder:1.1
    container_name: mailserver
    environment:
      - SMF_CONFIG=@mailserver1.org:mypersonalemail@gmail.com;@mailserver2.org:mypersonalemail@gmail.com
    ports:
      - "25:25"
    volumes:
      - "./hostname:/etc/hostname:ro"
    network_mode: host
    restart: always
```

And this is the hostname file:

```
mailserver1.org
mailserver2.org
```

It seems that some emails have arrived, I will do more tests in the next days
