### ISSUE TITLE
Email forwarded by SMF lands in target spam folder

### ISSUE THREAD

**Issue by steilerDev** [huan/docker-simple-mail-forwarder#108]
Hi All!

I've set up SMF succesfully now, however I have the issue that the mail fowarded by SMF lands in my target's mail account spam folder. Not sure if this is a limitation or a misconfiguration on my side. Looking for your input/guidance if I'm missing something.

Certificates come from letsencrypt, DKIM (with keylength 1024 bit) added to DNS and all checks on startup are successful.

My docker-compose.yml at the moment:
```
version: '2'
services:
  mail-forwarder:
    image: zixia/simple-mail-forwarder:latest
    container_name: mail-forwarder
    restart: unless-stopped
    ports:
      - "25:25"
    environment:
      SMF_CONFIG: "@some.tld:account@another.tld"
      SMF_DOMAIN: "mail-relay.somethird.tld"
      TZ: "Europe/Berlin"
      SMF_SRS: "true"
      SMF_POSTFIXMAIN_sender_canonical_maps: "tcp:localhost:10001"
      SMF_POSTFIXMAIN_sender_canonical_classes: "envelope_sender"
      SMF_POSTFIXMAIN_recipient_canonical_maps: "tcp:localhost:10002"
      SMF_POSTFIXMAIN_recipient_canonical_classes: "envelope_recipient,header_recipient"
    volumes:
      - <path>/:/etc/postfix/cert/
      - <path>/:/etc/postfix/letsencrypt-cert/
      - <path>/:/var/db/dkim/
networks:
  default:
    external:
      name: steilerGroup
```
