### ISSUE TITLE
use as SMTP server?

### ISSUE THREAD

**Issue by Jeffrey04** [huan/docker-simple-mail-forwarder#67]
Just want to check if I read correctly, besides forwarding mail, does the container also act as a SMTP server where I can setup my client to use the password in `SMF_CONFIG `?

Couldn't really get mail being forwarded after the setup however, not sure if I doing this correctly. The internal test cases all passes, but mail doesn't get forwarded / sent.

this is my docker-compose snippet

```
    mail:
        image: "zixia/simple-mail-forwarder"
        ports:
            - "587:25"
        restart: always
        tty: true
        environment:
            SMF_CONFIG: "$origin_email:$dest_email:randompassword!"
            SMF_DOMAIN: coolsilon.com
            TZ: "Asia/Kuala_Lumpur"
        volumes:
            - "/var/lib/docker-files/letsencrypt/:/etc/postfix/cert/"
```

and the respective DNS

```
root@doraemon:/var/lib/docker-files/coolsilon# dig +short MX coolsilon.com
10 mail.coolsilon.com.
root@doraemon:/var/lib/docker-files/coolsilon# dig +short CNAME mail.coolsilon.com
coolsilon.com.
root@doraemon:/var/lib/docker-files/coolsilon# dig +short TXT coolsilon.com
"v=spf1 mx ~all"
```

I found a script online to send mail through SMTP, while the script executed without an error returned, but I don't see the test mail in my mailbox.

```
# Import smtplib for the actual sending function
import smtplib
import ssl

# Import the email modules we'll need
from email.mime.text import MIMEText

import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Open a plain text file for reading.  For this example, assume that
# the text file contains only ASCII characters.
msg = MIMEText("Test")

me = "origin@example.org"
you = "dest@example.com"

# me == the sender's email address
# you == the recipient's email address
msg['Subject'] = 'Test'
msg['From'] = me
msg['To'] = you

# Send the message via our own SMTP server, but don't include the
# envelope header.
with smtplib.SMTP("coolsilon.com", 587) as server:
    print('login', server.login(me, '***!'))
    print('send', server.sendmail(me, [you], msg.as_string()))
    server.quit()
```
