### ISSUE TITLE
Allow for setting any Postfix variables in the config file

### ISSUE THREAD

**Issue by knipknap** [huan/docker-simple-mail-forwarder#74]
Stolen from [wader/postfix-relay](https://github.com/wader/postfix-relay/blob/master/run), I propose to add the following line to your entrypoint.sh:

```
for e in ${!POSTFIX_*} ; do postconf -e "${e:8}=${!e}" ; done
```

This allows for setting up postfix in a Docker swarm / compose, without having to mount a whole configfile. Usage:

```
  mail_relay:
    image: zixia/simple-mail-forwarder:1.1
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.tcp.routers.mail_relay.rule=HostSNI(`*`)
        - traefik.tcp.routers.mail_relay.entrypoints=smtp
        - traefik.tcp.routers.mail_relay.service=mail_relay
        - traefik.tcp.services.mail_relay.loadbalancer.server.port=25
    environment:
      - SMF_DOMAIN=domain1.com
      - |
        SMF_CONFIG=
        sam@domain1.com:foo@gmail.com;
        sam@domain2.com:foo@gmail.com;
      - POSTFIX_myhostname=smtp.domain1.com
      - POSTFIX_relay_domains="domain1.com domain2.com"
      - POSTFIX_smtpd_recipient_restrictions=permit_mynetworks, permit_sasl_authenticated
```

(note the last three lines)
